### ISSUE TITLE
Best way to have callback span multiple starts

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/bluesky-browser#13]
We may want a single callback to span multiple runs. For instance if we take a single shot per RE call but want to put them together in a scatter plot. Currently a callback clears/refreshes itself upon start document.

## Expected Behavior
Have a way to specify if not to clear/refresh when we get a start in.

## Current Behavior
Callback refresh on start.

## Possible Solution
Have a dedicated clearing mechanism, which may or may not be called (potentially using a separate 'clear' document/callback message)

## Context
Often we make many start documents even though we wish the data to be visualized together. Eg a scan on a grid with many samples may get a start document per sample (so as to preserve the search ability of the sample data) but we want to visualize the max intensity per grid position as a whole.

**Comment by tacaswell** [comment]
I am not sure that clearing callback objects is the right path here, I think it is better to just create new instances when you want a clean instance.
