### ISSUE TITLE
More Demo Suggestions

### ISSUE THREAD

**Issue by awalter-bnl** [bluesky/bluesky-browser#2]
Here a my thoughts on the work so far:
1. First point I appear to have found a bug. After running the browser I can repeatably cause the window to crash (close) with the following steps,
 - rescaling to see all of the columns
 - double clicking on scan_id 5
 - selecting catalog 'xyz'
 - clicking on scan_id 1
see the output of the command line below  for this entire process

2. A few parts I really like.
 - The 'open' and 'Add to tab' buttons that appear when a scan is selected in the search results.   
 - The way that the different 'plots' appear as different sub tabs (which keeps things neat)
 - The 'open overplotted' button,  and the layout of the different .
 - The way in an 'overplotted' tab that the different added runs are all shown as different windows in the 'Header' and 'Baseline' Tabs.

3. I know this will recieve some push back, but I think it is a very important point to note. labelling tabs and or figures in a plot based on 'Unique ID' will be wildly unpopular on the floor
 - This is because the unique id, although guaranteed to be unique is not an easily remebered/understood number. I am not aware of _anyone_ currently using bluesky who references using UID they all use the more human readable scan_id.
 - As we are now talking of allowing different catalogs to be used together, which makes the scan_id even less unique, I recommend labelling the tabs and plots using a combination of catalog name and scan_id (or date and scan_id) instead of UID, for tabs and 'scan_ID[UID]' for plots.
 - On a second note here I am not a great fan of the word 'Transient' in front of 'Scan ID' in the list search results, but am not wiling to fall on my sword on that one !-).

4.  I think another few bugs occur for the over-plotting tabs.
 - The baseline tab does not automatically update with new entries like the 'Header' tab.
 - New plot tabs are not created when a subsequent scan has a different 'detector'.
 - Trying to search with a query while an overplotted tab is open, or even once the 'overplotting' tab is available crashes the GUI.

> alwalter@awalter01:~/NSLS-II/bluesky-browser$ bluesky-browser --demo
/home/alwalter/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Serializing example data into directory /tmp/tmpqf4dbhct
Demo Proxy is listening on port 40423 and publishing to 37747.
Demo acquisition has started.
Query {'time': {'$gte': 1556192475, '$lt': 1557402075}} -> 6 results
New streaming Run: uid='b20bbaf7-20b2-40f9-91b4-5ca83cf82a50'
Streaming Run ignored because Streaming is disabled.
Query {'time': {'$gte': 1556192475, '$lt': 1557402075}} -> 1 results
dimensions: [[['time'], 'primary']]
plot det against time
Reloaded search results
Query {'time': {'$gte': 1556192475, '$lt': 1557402075}} -> 7 results
New streaming Run: uid='67050616-305b-4037-bb33-a43d2a2eec1f'
Streaming Run ignored because Streaming is disabled.
dimensions: [[['motor'], 'primary']]
plot det against motor
Query {'time': {'$gte': 1556192475, '$lt': 1557402075}} -> 1 results
Reloaded search results
Traceback (most recent call last):
  File "/home/alwalter/NSLS-II/bluesky-browser/bluesky_browser/search.py", line 181, in emit_selected_result
    for row in sorted(self.selected_rows)])
  File "/home/alwalter/NSLS-II/bluesky-browser/bluesky_browser/search.py", line 181, in <listcomp>
    for row in sorted(self.selected_rows)])
IndexError: list index out of range
Aborted

**Comment by danielballan** [comment]
1. Bug fixed in bb5cbd629f7f9cb6251e5dbf4a3743aa4ba1bf88 and 9ce00254f1e1ab25f4ce2153553041bc156cc839
2. Thanks!
3. Action item here is to make tab display title configurable via a menu, but use uid to disambiguate in select boxes. The word "Transient" will remain until we sort out a better way to deal with not-actually-unique label via a tagging system (discussion kicked off in Slack).
4. The crash was another symptom of the bugs fixed in (1)

> New plot tabs are not created when a subsequent scan has a different 'detector'.

Yes, this is tricky to resolve actually. I think this will just have a remain a limitation of "overplotting" for now: the first plot sets the axes, and _changing_ the axes in matplotlib is very hard. This can be revisited in a couple weeks.

**Comment by awalter-bnl** [comment]
Adding one more bug I just found. On overplotting tabs I found that multiple versions of the same data are added to the first 'Scalars v time` figures when 'adding to the tab'.

**Comment by danielballan** [comment]
Can you disambiguate "plots" into "figures" and "axes"?

**Comment by awalter-bnl** [comment]
does my edit above help?

**Comment by danielballan** [comment]
Yes, thanks. I think a fix for this will fall out easily from the "re-plotting" feature we hope to add next, because that will need to keep track of what was done where so it can redo it on demand.

**Comment by awalter-bnl** [comment]
closing this issue as all of the points appear to have been resolved.
