### ISSUE TITLE
crashed the application

### ISSUE THREAD

**Issue by prjemian** [bluesky/bluesky-browser#50]
Followed installation guidelines (revised per PR #49) on RHEL7 x86_64.

1. Application started and presented runs from some (demo?) databroker.  Good.
1. Lots of console traceback output as I moved mouse over the window.
1. Double clicked on ScanID 1
1. Tab opened in right-side panel: shows Header, Baseline, ...
1. Visual inspection of document content (in the different tabs) looks fine.
1. Crashed the application when I clicked the [x] box on the run's tab in right side panel.

This report on the console:

```
Traceback (most recent call last):
  File "/home/oxygen18/JEMIAN/sandbox/bluesky-browser/bluesky_browser/viewer/viewer.py", line 207, in close_tab
    self.parent().close_run_viewer(widget)
AttributeError: 'QSplitter' object has no attribute 'close_run_viewer'
Aborted
```

Very reproducible.

**Comment by danielballan** [comment]
Thanks for the report. I have reproduced it as you say and proposed a fix in #51. I believe that this used to work and that I unknowingly broke it in a refactor. It's time to add tests to this repo.
