### ISSUE TITLE
Interact with RemoteDispatcher and Publisher?

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/bluesky-browser#8]
Would it be possible to interact with the message buses? That way data could be sent onto the bus for analysis and received back from the bus for plotting. This could also support live data?

**Comment by danielballan** [comment]
It does now, unless I've misunderstood?

```
$ bluesky-browser --help
usage: bluesky-browser [-h] [-z ZMQ_ADDRESS] [--verbose] [--demo] catalog

Prototype bluesky data browser

positional arguments:
  catalog

optional arguments:
  -h, --help            show this help message and exit
  -z ZMQ_ADDRESS, --zmq-address ZMQ_ADDRESS
                        0MQ remote dispatcher address (host:port)
  --verbose, -v
  --demo                Launch the app with example data.

version 0.post128+g418aabe
```

**Comment by CJ-Wright** [comment]
Does it take messages from there as well and hand them to the RunRouter?

**Comment by danielballan** [comment]
Yes. The documents from 0MQ are pushed through the same RunRouter as the documents from "opening" a run in the search results.

**Comment by danielballan** [comment]
To be more specific, documents are piped from a 0MQ RemoteDispatcher into a Qt Signal

https://github.com/bluesky/bluesky-browser/blob/23faf61d4997a303d2f26c8591b05e692f073962/bluesky_browser/zmq.py#L16-L23

and consumed by the `Viewer` widget:

https://github.com/bluesky/bluesky-browser/blob/23faf61d4997a303d2f26c8591b05e692f073962/bluesky_browser/main.py#L93-L96
